name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'

    - name: Run tests
      run: go test

    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Login into the container registry
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          evandrolugli/devops-golang:${{ steps.generate_sha.outputs.sha }}
          evandrolugli/devops-golang:latest

    # - name: Build docker image
    #   run: docker build -t evandrolugli/devops-golang:${{ steps.generate_sha.outputs.sha }} .

    # - name: Push image
    #   run: |
    #     docker push evandrolugli/devops-golang:${{ steps.generate_sha.outputs.sha }}
    #     docker tag evandrolugli/devops-golang:${{ steps.generate_sha.outputs.sha }} evandrolugli/devops-golang:latest
    #     docker push evandrolugli/devops-golang:latest